"""protocol.yaml -> generated/link_msgs.h + link_msgs.c for the firmware.

The Python side reads protocol.yaml directly (groundstation/protocol/schema.py), so there is
no generated msgs.py; the C files are the only generated artefact.

    python tools/gen_protocol.py [out_dir]      # default: ground_station/generated
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from groundstation.protocol.schema import Schema  # noqa: E402

CTYPE = {"u8": "uint8_t", "i8": "int8_t", "u16": "uint16_t", "i16": "int16_t",
         "u32": "uint32_t", "i32": "int32_t"}
NBYTES = {"u8": 1, "i8": 1, "u16": 2, "i16": 2, "u32": 4, "i32": 4}


def generate(schema: Schema) -> tuple[str, str]:
    h = ["/* GENERATED by tools/gen_protocol.py from protocol.yaml. Do not edit. */",
         "#ifndef LINK_MSGS_H", "#define LINK_MSGS_H", "",
         "#include <stdbool.h>", "#include <stddef.h>", "#include <stdint.h>", "",
         f"#define LINK_PROTOCOL_HASH 0x{schema.hash:08X}u", ""]
    for ename, members in schema.enums.items():
        h.append(f"typedef enum {{")
        h += [f"    LINK_{ename.upper()}_{k} = {v}," for k, v in members.items()]
        h.append(f"}} link_{ename}_t;\n")
    h.append("typedef enum {")
    h += [f"    LINK_MSG_{m.name} = 0x{m.id:02X}," for m in schema.by_name.values()]
    h.append("} link_msg_id_t;\n")
    c = ['/* GENERATED by tools/gen_protocol.py from protocol.yaml. Do not edit. */',
         '#include "link_msgs.h"', ""]
    for m in schema.by_name.values():
        h.append(f"#define LINK_{m.name}_SIZE {m.struct.size}u")
        if not m.fields:
            continue
        h.append("typedef struct {")
        h += [f"    {CTYPE[f.type]} {f.name};" for f in m.fields]
        h.append(f"}} link_{m.name}_t;")
        h.append(f"size_t link_{m.name}_pack(const link_{m.name}_t *m, uint8_t *b);")
        h.append(f"bool link_{m.name}_unpack(link_{m.name}_t *m, const uint8_t *b, size_t len);\n")
        c.append(f"size_t link_{m.name}_pack(const link_{m.name}_t *m, uint8_t *b)\n{{\n    size_t i = 0u;")
        u = []
        for f in m.fields:
            n = NBYTES[f.type]
            c += [f"    b[i++] = (uint8_t)(((uint32_t)m->{f.name}) >> {8 * k}u);" for k in range(n)]
            terms = " | ".join(f"((uint32_t)b[i + {k}u] << {8 * k}u)" for k in range(n))
            u.append(f"    m->{f.name} = ({CTYPE[f.type]})({terms});\n    i += {n}u;")
        c.append("    return i;\n}\n")
        c.append(f"bool link_{m.name}_unpack(link_{m.name}_t *m, const uint8_t *b, size_t len)\n{{\n"
                 f"    size_t i = 0u;\n    if (len != LINK_{m.name}_SIZE) {{ return false; }}")
        c += u
        c.append("    (void)i;\n    return true;\n}\n")
    h.append("\n#endif")
    return "\n".join(h) + "\n", "\n".join(c) + "\n"


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "generated"
    out.mkdir(exist_ok=True)
    header, source = generate(Schema.load())
    (out / "link_msgs.h").write_text(header)
    (out / "link_msgs.c").write_text(source)
    print(f"wrote {out}/link_msgs.h and link_msgs.c")
